// <auto-generated />
namespace DOD_Maker_Hamza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class savingMyDODs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(savingMyDODs));
        
        string IMigrationMetadata.Id
        {
            get { return "201712091936375_savingMyDODs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
